// <auto-generated />
using System;
using EcoWatt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EcoWatt.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoWatt.Models.Consumo", b =>
                {
                    b.Property<int>("ConsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumoId"));

                    b.Property<DateTime>("Data_Consumo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_consumo");

                    b.Property<string>("Hora_Consumo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("qt_horas_uso");

                    b.Property<int>("Quantidade_Watts")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("vl_consumo_watts");

                    b.HasKey("ConsumoId");

                    b.ToTable("_Consumo");
                });

            modelBuilder.Entity("EcoWatt.Models.Eletrodomesticos", b =>
                {
                    b.Property<int>("EletrodomesticosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EletrodomesticosId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_categoria");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_modelo");

                    b.Property<string>("Nome_Aparelho")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_nome");

                    b.Property<int>("Valor_Consumo_Watts")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("vl_aparelho_consumo_watts");

                    b.HasKey("EletrodomesticosId");

                    b.ToTable("_Eletrodomesticos");
                });

            modelBuilder.Entity("EcoWatt.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cd_cep");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cd_senha");

                    b.HasKey("UsuarioId");

                    b.ToTable("_Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
